package com.microstrategy.samples.beans.reportbean;

import com.microstrategy.samples.sessions.SessionManager;
import com.microstrategy.web.beans.BeanFactory;
import com.microstrategy.web.beans.ReportBean;
import com.microstrategy.web.beans.WebBeanException;
import com.microstrategy.web.objects.EnumWebReportExecutionModes;
import com.microstrategy.web.objects.WebIServerSession;
import com.microstrategy.web.objects.WebObjectsException;
import com.microstrategy.web.objects.WebReportInstance;
import com.microstrategy.webapi.EnumDSSXMLExecutionFlags;
import com.microstrategy.webapi.EnumDSSXMLResultFlags;

public class GetReportSQL {

  public static void main(String[] args) {
    // Set server connection information
    final String INTELLIGENCE_SERVER_NAME = "10.23.6.68";
    final String PROJECT_NAME = "MicroStrategy Tutorial";
    final String MICROSTRATEGY_USERNAME = "Administrator";
    final String MICROSTRATEGY_PASSWORD = "";

    //Report ID to get the SQL
    String reportID = "3303EE9D4011202E2CDBF08253B8AB8A";
    
    // Create an IServer session
    WebIServerSession iServerSession = SessionManager.getSessionWithDetails(INTELLIGENCE_SERVER_NAME, PROJECT_NAME, MICROSTRATEGY_USERNAME, MICROSTRATEGY_PASSWORD);

    //Obtaining sql sentence used in the report.
    String sql = getSQLFromReport(iServerSession, reportID);
    System.out.println("SQL generated: " + sql);
  }

  /**
   * Returns the SQL generated by a report instance.
   * @param iServerSession
   * @param reportID
   * @return String sql - SQL generated by a report.
   */
  public static String getSQLFromReport(WebIServerSession iServerSession, String reportID) {	
    ReportBean reportBean = (ReportBean) BeanFactory.getInstance().newBean("ReportBean");
    reportBean.setObjectID(reportID);
    reportBean.setSessionInfo(iServerSession);
    reportBean.setExecutionMode(EnumWebReportExecutionModes.REPORT_MODE_DEFAULT);
    String sql = null;
    try {
      reportBean.collectData();
      WebReportInstance reportInstance = reportBean.getReportInstance();
      reportBean.setResultFlags(EnumDSSXMLResultFlags.DssXmlResultXmlSQL);
      reportBean.setExecutionFlags(EnumDSSXMLExecutionFlags.DssXmlExecutionGenerateSQL);
      sql = reportInstance.getResults().getSQL();
    } catch (WebBeanException | WebObjectsException e) {
      e.printStackTrace();
    }

    return sql;
}
	

}
